### ISSUE TITLE
Can't use pm_pbar with starmap

### ISSUE THREAD

**Issue by weber8thomas** [zeehio/parmap#20]
Hi,

Thanks for the work, your library is very useful :)

I have a little problem with `starmap` : I have this issue when I want to display `pm_pbar=True`
```
Traceback (most recent call last):
  File "convert.py", line 126, in <module>
    pm_processes=multiprocessing.cpu_count()
  File "/home/weber/anaconda3/lib/python3.7/site-packages/parmap/parmap.py", line 312, in starmap
    return _map_or_starmap(function, iterables, args, kwargs, "starmap")
  File "/home/weber/anaconda3/lib/python3.7/site-packages/parmap/parmap.py", line 239, in _map_or_starmap
    num_tasks = len(iterable)
TypeError: object of type 'zip' has no len()
```
The extract of my code is here : 

```
...
hum_id_dict = hum_id.to_dict()
d = manager.dict()
log = manager.list()

z = starmap(convert,
            zip(hum_id_dict.values(), itertools.repeat(log), itertools.repeat(d)),
            pm_pbar=True,
            )
```
Is there a solution to bypass the zip problem please ? 

Thanks !!

**Comment by zeehio** [comment]
I guess converting the zip iterable to a list would work:

```
z = starmap(convert,
            list(zip(hum_id_dict.values(), itertools.repeat(log), itertools.repeat(d))),
            pm_pbar=True,
            )
```
